// lib/categoryOptions.js
export const categoryOptions = [
  { id: "rent", name: "Rent", icon: "🏠" },
  { id: "groceries", name: "Groceries", icon: "🛒" },
  { id: "utilities", name: "Utilities", icon: "💡" },
  { id: "mobile", name: "Mobile/Internet", icon: "📶" },
  { id: "fuel", name: "Fuel", icon: "⛽" },
  { id: "transport", name: "Transportation", icon: "🚕" },
  { id: "lunch", name: "Lunch/Dinner", icon: "🍽️" },
  { id: "snacks", name: "Snacks", icon: "🍩" },
  { id: "coffee", name: "Coffee/Tea", icon: "☕" },
  { id: "restaurant", name: "Restaurant", icon: "🍴" },
  { id: "takeout", name: "Takeout/Delivery", icon: "🛵" },
  { id: "clothing", name: "Clothing", icon: "👕" },
  { id: "footwear", name: "Footwear", icon: "👟" },
  { id: "electronics", name: "Electronics", icon: "📱" },
  { id: "accessories", name: "Accessories", icon: "👜" },
  { id: "medicines", name: "Medicines", icon: "💊" },
  { id: "doctor", name: "Doctor Visit", icon: "🩺" },
  { id: "fitness", name: "Gym/Fitness", icon: "🏋️" },
  { id: "movies", name: "Movies", icon: "🎬" },
  { id: "subscriptions", name: "Subscriptions", icon: "🎧" },
  { id: "travel", name: "Travel", icon: "✈️" },
  { id: "hotel", name: "Hotel", icon: "🏨" },
  { id: "books", name: "Books", icon: "📚" },
  { id: "courses", name: "Courses", icon: "🧑‍🏫" },
  { id: "gifts", name: "Gifts", icon: "🎁" },
  { id: "donations", name: "Donations", icon: "❤️" },
  { id: "personalcare", name: "Personal Care", icon: "🧖‍♂️" },
];
